/*
SQLyog Enterprise - MySQL GUI v8.1 
MySQL - 5.5.5-10.4.27-MariaDB : Database - bd_dashacad_03
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`bd_dashacad_03` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

USE `bd_dashacad_03`;

/*Table structure for table `tbl_alternativas` */

DROP TABLE IF EXISTS `tbl_alternativas`;

CREATE TABLE `tbl_alternativas` (
  `ALT_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `ALT_DESCRICAO` varchar(500) DEFAULT NULL,
  `ALT_STATUS` varchar(10) DEFAULT NULL,
  `QUE_CODIGO` int(11) NOT NULL,
  `ALT_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `ALT_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  PRIMARY KEY (`ALT_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_ALT` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_ALT` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_ALT` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_ALT` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_disciplina` */

DROP TABLE IF EXISTS `tbl_disciplina`;

CREATE TABLE `tbl_disciplina` (
  `DIS_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DIS_NOME` varchar(50) DEFAULT NULL,
  `DIS_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `DIS_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  PRIMARY KEY (`DIS_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_DIS` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_DIS` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_DIS` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_DIS` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_formulario` */

DROP TABLE IF EXISTS `tbl_formulario`;

CREATE TABLE `tbl_formulario` (
  `FOR_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `FOR_TITULO` varchar(100) DEFAULT NULL,
  `FOR_DESCRICAO` varchar(500) DEFAULT NULL,
  `FOR_DT_ENTREGA` date DEFAULT NULL,
  `TUR_CODIGO` int(11) NOT NULL,
  `DIS_CODIGO` int(11) NOT NULL,
  `FOR_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `FOR_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  PRIMARY KEY (`FOR_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_FOR` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_FOR` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_FOR` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_FOR` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_questao` */

DROP TABLE IF EXISTS `tbl_questao`;

CREATE TABLE `tbl_questao` (
  `QUE_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `FOR_CODIGO` int(11) DEFAULT NULL,
  `QUE_DESCRICAO` varchar(500) DEFAULT NULL,
  `QUE_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `QUE_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  PRIMARY KEY (`QUE_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_QUE` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_QUE` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_QUE` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_QUE` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_resposta_aluno` */

DROP TABLE IF EXISTS `tbl_resposta_aluno`;

CREATE TABLE `tbl_resposta_aluno` (
  `RES_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `USU_CODIGO` int(11) NOT NULL,
  `FOR_CODIGO` int(11) NOT NULL,
  `QUE_CODIGO` int(11) NOT NULL,
  `ALT_CODIGO` int(11) NOT NULL,
  `RES_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `RES_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  PRIMARY KEY (`RES_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_RES` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_RES` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_RES` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_RES` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_turma` */

DROP TABLE IF EXISTS `tbl_turma`;

CREATE TABLE `tbl_turma` (
  `TUR_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `TUR_SERIE` varchar(20) DEFAULT NULL,
  `TUR_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `TUR_DTALT` timestamp NULL DEFAULT NULL,
  `USU_CODIGO_ALT` int(11) NOT NULL,
  `USU_CODIGO_CAD` int(11) NOT NULL,
  PRIMARY KEY (`TUR_CODIGO`),
  KEY `FK_USU_CODIGO_ALT_TUR` (`USU_CODIGO_ALT`),
  KEY `FK_USU_CODIGO_CAD_TUR` (`USU_CODIGO_CAD`),
  CONSTRAINT `FK_USU_CODIGO_ALT_TUR` FOREIGN KEY (`USU_CODIGO_ALT`) REFERENCES `tbl_usuario` (`USU_CODIGO`),
  CONSTRAINT `FK_USU_CODIGO_CAD_TUR` FOREIGN KEY (`USU_CODIGO_CAD`) REFERENCES `tbl_usuario` (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Table structure for table `tbl_usuario` */

DROP TABLE IF EXISTS `tbl_usuario`;

CREATE TABLE `tbl_usuario` (
  `USU_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `USU_NOME` varchar(50) DEFAULT NULL,
  `USU_EMAIL` varchar(50) DEFAULT NULL,
  `USU_SENHA` varchar(10) DEFAULT NULL,
  `USU_FOTO` longblob DEFAULT NULL,
  `USU_TIPO` varchar(10) NOT NULL,
  `TUR_CODIGO` int(11) NOT NULL,
  `USU_DTCAD` timestamp NULL DEFAULT current_timestamp(),
  `USU_DTALT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USU_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
